# Generated by Django 4.2 on 2024-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_preferences_task_reminder_applicationdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='preferred_days',
            field=models.CharField(blank=True, help_text='Enter preferred days separated by comma (e.g., Monday,Wednesday)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Enter preferred time for tasks', null=True),
        ),
    ]
