# Generated by Django 4.2 on 2024-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myuser_preferred_days_myuser_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
