# Generated by Django 4.2 on 2024-04-15 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_task_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='preferred_days',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='preferred_time',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preferred_days', models.CharField(max_length=255)),
                ('preferred_time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
