# Generated by Django 4.2 on 2024-04-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_myuser_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
    ]
