# Generated by Django 4.2 on 2024-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_myuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preferred_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
